app:
    resource: '@DondrekielBundle/Controller/'
    type: annotation

users:
    type:     rest
    host:     "%app_hostname%"
    resource: DondrekielBundle\Controller\StationController
    prefix:   rest