# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    dondrekiel.user.provider.class: DondrekielAdminBundle\Repository\TeamRepository
    dondrekiel.user.provider.entity.class: DondrekielAppBundle\Entity\Team
    dondrekiel_admin.menu_listener.class: DondrekielAdminBundle\EventListener\AdminMenuItemListListener
    dondrekiel_admin.twig_extension.class: DondrekielAdminBundle\Extensions\TwigExtensions

services:

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    DondrekielAppBundle\:
        resource: '../../src/DondrekielAppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/DondrekielAppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    DondrekielAppBundle\Controller\:
        resource: '../../src/DondrekielAppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    gos_web_socket_server.client_event.listener:
        class: DondrekielAppBundle\EventListener\DondrekielEventListener
        tags:
            - { name: kernel.event_listener, event: 'gos_web_socket.client_connected', method: onClientConnect }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_disconnected', method: onClientDisconnect }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_error', method: onClientError }
            - { name: kernel.event_listener, event: 'gos_web_socket.server_launched', method: onServerStart }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_rejected', method: onClientRejected }


    pdo:
        class: PDO
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - '%database_user%'
            - '%database_password%'
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [!service { class: PDO, factory: 'database_connection:getWrappedConnection' }, {lock_mode: 0}]


    dondrekiel.twig.extension:
        class:        %dondrekiel_admin.twig_extension.class%
        arguments:     [ "@doctrine.orm.entity_manager" ]
        tags:
            -  { name: twig.extension }

    dondrekiel_admin.menu_listener:
        class: %dondrekiel_admin.menu_listener.class%
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }

