services:
    dondrekiel.rpc_dondrekiel_service:
        class: DondrekielAppBundle\RPC\DondrekielService
        tags:
            - { name: gos_web_socket.rpc }

    dondrekiel.topic_dondrekiel_service:
        class: DondrekielAppBundle\Topic\DondrekielTopic
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
            - "@security.token_storage"
            - "@doctrine"
            - '@?monolog.logger.websocket'
        tags:
            - { name: gos_web_socket.topic }

    dondrekiel.periodic_dondrekiel_service:
        class: DondrekielAppBundle\Periodic\DondrekielPeriodic
        tags:
            - { name: gos_web_socket.periodic }