services:
    dondrekiel.rpc_dondrekiel_service:
        class: DondrekielAppBundle\RPC\DondrekielService
        tags:
            - { name: gos_web_socket.rpc }

    dondrekiel.topic_dondrekiel_service:
        class: DondrekielAppBundle\Topic\DondrekielTopic
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
            - "@security.token_storage"
            - "@doctrine"
            - '@?monolog.logger.websocket'
        tags:
            - { name: gos_web_socket.topic }

    dondrekiel.login_event_listener:
        class: DondrekielAppBundle\EventListener\DondrekielLoginEventListener
        arguments:
            - "@doctrine"
            - "@security.encoder_factory"
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
